### ISSUE TITLE
Internal crash for "previously declared class name" friend specifier

### ISSUE THREAD

**Issue by benjaminulmer** [marzer/poxy#37] opened 2024-09-04 15:36 UTC
## Environment

Python 3.10.12
Poxy 0.18.0
Doxygen 1.12.0

## Describe the bug

Making a friend declaration using a _previously declared class name_ [simple type specifier](https://en.cppreference.com/w/cpp/language/declarations#Specifiers) causes poxy to encounter an internal error. Changing the friend declaration to an elaborated type specifier fixes the issue.

```C++
#pragma once

namespace test {

struct ForwardDec;

struct MyType {
    friend ForwardDec;
    // friend struct ForwardDec;
    // ^^^ this line works
};

}  // namespace test
```

## Additional information

Reproducing repo available [here](https://github.com/benjaminulmer/poxy-bugs)

## `--bug-report`
[poxy_bug_report.zip](https://github.com/user-attachments/files/16873238/poxy_bug_report.zip)

-   [X] I have attached the zip file generated when using the --bug-report option

**Comment by marzer** [comment] 2024-09-04 18:26
Ohhh, interesting. @mosra is this something that's happening in m.css, or a side-effect of Doxygen bugs? here's the stderr fronm m.css:

```
    DEBUG:root:Parsing configuration from /tmp/poxy/bug_report/temp/Doxyfile
    DEBUG:root:Extracting metadata from friends_8hpp.xml
    DEBUG:root:Extracting metadata from index.xml
    DEBUG:root:Extracting metadata from structtest_1_1_my_type.xml
    DEBUG:root:Extracting metadata from namespacetest.xml
    DEBUG:root:Ignoring Doxyfile.xml
    DEBUG:root:Parsing friends_8hpp.xml
    DEBUG:asyncio:Using selector: EpollSelector
    DEBUG:root:Parsing index.xml
    DEBUG:asyncio:Using selector: EpollSelector
    DEBUG:asyncio:Using selector: EpollSelector
    DEBUG:asyncio:Using selector: EpollSelector
    DEBUG:asyncio:Using selector: EpollSelector
    DEBUG:asyncio:Using selector: EpollSelector
    DEBUG:asyncio:Using selector: EpollSelector
    DEBUG:root:Parsing structtest_1_1_my_type.xml
    Traceback (most recent call last):
      File "/home/benjaminulmer/.cache/pypoetry/virtualenvs/bgcore-1rZqfR6r-py3.10/lib/python3.10/site-packages/poxy/mcss/documentation/doxygen.py", line 4059, in <module>
        run(state, templates=os.path.abspath(args.templates), wildcard=args.wildcard, index_pages=args.index_pages, search_merge_subtrees=not args.search_no_subtree_merging, search_add_lookahead_barriers=not args.search_no_lookahead_barriers, search_merge_prefixes=not args.search_no_prefix_merging)
      File "/home/benjaminulmer/.cache/pypoetry/virtualenvs/bgcore-1rZqfR6r-py3.10/lib/python3.10/site-packages/poxy/mcss/documentation/doxygen.py", line 3916, in run
        parsed = parse_xml(state, file)
      File "/home/benjaminulmer/.cache/pypoetry/virtualenvs/bgcore-1rZqfR6r-py3.10/lib/python3.10/site-packages/poxy/mcss/documentation/doxygen.py", line 3049, in parse_xml
        var = parse_var(state, memberdef)
      File "/home/benjaminulmer/.cache/pypoetry/virtualenvs/bgcore-1rZqfR6r-py3.10/lib/python3.10/site-packages/poxy/mcss/documentation/doxygen.py", line 2202, in parse_var
        assert element.tag == 'memberdef' and element.attrib['kind'] == 'variable'
    AssertionErro
```

**Comment by mosra** [comment] 2024-09-10 08:40
It's a behavior change in newer Doxygen, it used to treat those as "variables" (yes), now it treats them as "friends". The assertion expects the former. Ultimately, Doxygen fails to extract anything meaningful from those anyway so m.css ignores all friend declarations. 

I'll see if I'm able make any progress on the giant pile of TODOs and workarounds required for Doxygen 1.9+, will comment back here once I have something. Until then, the workaround is either adding a `struct`, or excluding the friend declarations from Doxygen altogether with an ifdef, for example.

**Comment by marzer** [comment] 2024-09-10 08:42
> Until then, the workaround is either adding a struct

Yeah, to be honest, I didn't even realize this C++11-style of `friend` declaration was possible until this bug report. I've literally never seen this "simple" form of `friend` delaration in the wild 😅

**Comment by mosra** [comment] 2024-09-10 08:58
I use it extensively myself, a nice side effect is that this way you don't accidentally forward-declare something that doesn't exist.

Hmm... I'm trying to reproduce using my own test suite with 1.12 now and I'm not getting the `<memberdef kind="friend"` like in the ZIP file, but `kind="variable"` like the assert expects. I wonder what's to blame, if it's some insane interaction with some random other setting or whatnot.

**Comment by mosra** [comment] 2024-09-10 10:56
Now I'm fixing a bug where Doxygen fails to recognize an end of an inline code block, causing the rest of the page to be wrapped in `<code>`, completely giving up on parsing anything after. Followed by a similar bug where Doxygen interprets `Class<U>` as start of an underlined text ... until the end of the page.

**Comment by marzer** [comment] 2024-09-10 13:25
> Doxygen interprets Class<U> as start of an underlined text

we should have never given rocks the ability to think

**Comment by mosra** [comment] 2024-09-10 13:46
In retrospect the `<U>` is obvious, should always have behaved that way, not sure why it didn't until now. (And that's my personal problem with Markdown and its implicit HTML support, just too many tags and other footguns to type by accident.)

I'm now bisecting those bugs down to a concrete commit between Doxygen 1.8 and 1.12, once I have those squashed I'll tackle this one too. I'm hopeful that 1.12 might actually be _the_ release that _finally_ works again for all my use cases.

**Comment by mosra** [comment] 2024-09-13 13:24
Just FYI, I didn't give up, just slowly getting there. Didn't manage to reproduce this particular bug yet, but found many others. Watch https://github.com/mosra/m.css/issues/215 for progress.

**Comment by mosra** [comment] 2024-09-15 11:46
I'm sorry, I just cannot reproduce this on my end.

Took the code from https://github.com/benjaminulmer/poxy-bugs, tried with (modified) Doxyfile from the ZIP file as well as a hand-crafted minimal Doxyfile that looked like this

```ini
INPUT                   = friend/friends.hpp
AUTOLINK_SUPPORT        = NO
QUIET                   = YES
GENERATE_HTML           = NO
GENERATE_LATEX          = NO
GENERATE_XML            = YES
XML_PROGRAMLISTING      = NO
CASE_SENSE_NAMES        = YES
```

And in both cases I get 

```xml
    <sectiondef kind="public-attrib">
      <memberdef kind="variable" id="structtest_1_1MyType_1af90e90123bb9d05c344bc4915dd2ba4f" prot="public" static="no" mutable="no">
      <!--             ^^^^^^^^ *not* a friend here -->
        <type>friend</type>
        <definition>friend test::MyType::ForwardDec</definition>
        <argsstring></argsstring>
```

I tried with both Doxygen 1.11 and 1.12 from ArchLinux repos, as well as my own fork. Neither of them produces `<memberdef kind="friend">` in the output. 

I have only one idea why that could be, assuming your 1.12 is indeed the 1.12 tag, and not some random (and unfortunately broken) commit between 1.11 and 1.12 (which would report itself as 1.12 as well). Given that the XMLs in the ZIP look significantly different than the XMLs I get by running Doxygen directly, I suspect that *poxy itself* is doing some patching on them, which then results in this being changed? And by running Doxygen directly, without either m.css or poxy on top, I just don't get that output? @marzer is that possible?

**Comment by marzer** [comment] 2024-09-15 12:04
@mosra Yeah, it's possible. There's a number of pre-emptive fixes for various type system mismatches. Quite possible that something else I'm accounting for is breaking this use-case 😅  I'll have a look.

**Comment by mosra** [comment] 2024-09-15 12:07
Bold suggestion: could the original XMLs be backed up somewhere and then included in the bugreport zip? Possibly ran through the same pretty printer so they can be easily diffed for comparison.

**Comment by marzer** [comment] 2024-09-15 12:12
> Bold suggestion: could the original XMLs [...]

That's a good idea. Would be relatively easy to implement.

> which side is to blame, whether doxygen itself, m.css or poxy :)

After a brief look, I think it might be my fault after all. There's some code that handles doxygen leaving extraneous keywords in types, and it may be too overzealous in the `friend`-case. Testing it now 😄

**Comment by mosra** [comment] 2024-09-15 12:21
> There's some code that handles doxygen leaving extraneous keywords in types

I think that should be all handled by m.css by now (I think you even contributed that?), the last bug I found got fixed in mosra/m.css@53ac5a6b1a4951282b5cde6a3a8c4813bed9adbe.

And since 1.11, Doxygen does that clean up on its own, which I adapted to in mosra/m.css@fc372e638325584108e8b3b4648b47ed22929cfb, so in case you still need that for certain cases (and it can't be fixed in m.css), you could version-limit it at least.

**Comment by marzer** [comment] 2024-09-15 12:30
> I think you even contributed that?

Yep! It was based on my findings in dealing with it in poxy. There was some historical reason why I left the handling for it also in poxy, but I can't think what it was at the moment.

On an unrelated note, here's my nightmarish workaround for the `<member> -> <memberdef>` thing:

https://github.com/marzer/poxy/commit/b952317125ff0533dccf26344d00d76903d58a6b#diff-d8062028ff90cbd259045873792a5136f9add44aa928b1bed8a301ed1b3aea2aR470-R540

😅

**Comment by mosra** [comment] 2024-09-15 12:48
Yeah I saw that. Definitely wouldn't want to maintain that on my end, sweating just from imagining the interesting ways in which it could break on the next Doxygen update.

**Closed** 2024-09-15 15:02 UTC
Labels: bug

**Comment by benjaminulmer** [comment] 2024-09-17 14:41
Thanks for the quick fix @mosra and @marzer
